
export enum errors {
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    GENERAL_ERROR = "GENERAL_ERROR",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
}
